PATH = 'resources/'
MAX_LEN = 200
EPOCH = 5
BATCH_SIZE = 4
EMBEDDING_DIM = 512

# FILES
CNN_MODEL = 'CNN_MODEL.keras'
LSTM_MODEL = 'LSTM_MODEL.keras'
BILSTM_MODEL = 'BILSTM_MODEL.keras'
CNN_BILSTM_MODEL = 'CNN_BILSTM_MODEL.keras'

CNN_REPORT = 'CNN_REPORT.txt'
LSTM_REPORT = 'LSTM_REPORT.txt'
BILSTM_REPORT = 'BILSTM_REPORT.txt'
CNN_BILSTM_REPORT = 'CNN_BILSTM_REPORT.txt'
TRAINABLE = True
