PATH = 'resources/'
MAX_LEN = 200
EPOCH = 100
BATCH_SIZE = 4
EMBEDDING_DIM = 300
TRAINABLE = True
STOP_PATIENCE=10

# FILES
CNN_MODEL = 'CNN_MODEL.keras'
LSTM_MODEL = 'LSTM_MODEL.keras'
BILSTM_MODEL = 'BILSTM_MODEL.keras'
ENSEMBLE_CNN_BILSTM_MODEL = 'ENSEMBLE_CNN_BILSTM_MODEL.keras'
FUSION_CNN_BILSTM_MODEL = 'FUSION_CNN_BILSTM_MODEL.keras'
GLOVE_MODEL = 'GLOVE_MODEL.model'

REPORT = 'glove/reports/'
MODEL = 'glove/models/'
MODEL_IMAGE = 'glove/model_images/'
CHART = 'glove/charts/'

CNN_REPORT = 'CNN_REPORT.txt'
LSTM_REPORT = 'LSTM_REPORT.txt'
BILSTM_REPORT = 'BILSTM_REPORT.txt'
ENSEMBLE_CNN_BILSTM_REPORT = 'ENSEMBLE_CNN_BILSTM_REPORT.txt'
FUSION_CNN_BILSTM_REPORT = 'FUSION_CNN_BILSTM_REPORT.txt'

CNN_IMAGE = 'CNN_IMAGE.png'
LSTM_IMAGE = 'LSTM_IMAGE.png'
BILSTM_IMAGE = 'BILSTM_IMAGE.png'
ENSEMBLE_CNN_BILSTM_IMAGE = 'ENSEMBLE_CNN_BILSTM_IMAGE.png'
FUSION_CNN_BILSTM_IMAGE = 'FUSION_CNN_BILSTM_IMAGE.png'

CNN_CHART = 'CNN_CHART.png'
LSTM_CHART = 'LSTM_CHART.png'
BILSTM_CHART = 'BILSTM_CHART.png'
ENSEMBLE_CNN_BILSTM_CHART = 'ENSEMBLE_CNN_BILSTM_CHART.png'
FUSION_CNN_BILSTM_CHART = 'FUSION_CNN_BILSTM_CHART.png'