PATH = 'resources/'
MAX_LEN = 200
EPOCH = 100
BATCH_SIZE = 4
EMBEDDING_DIM = 200

# FILES
CNN_MODEL = 'CNN_MODEL_GLOVE.keras'
LSTM_MODEL = 'LSTM_MODEL_GLOVE.keras'
BILSTM_MODEL = 'BILSTM_MODEL_GLOVE.keras'
CNN_BILSTM_MODEL = 'CNN_BILSTM_MODEL_GLOVE.keras'

CNN_REPORT = 'CNN_REPORT_GLOVE.txt'
LSTM_REPORT = 'LSTM_REPORT_GLOVE.txt'
BILSTM_REPORT = 'BILSTM_REPORT_GLOVE.txt'
CNN_BILSTM_REPORT = 'CNN_BILSTM_REPORT_GLOVE.txt'
TRAINABLE = True
