PATH = 'resources/'
MAX_LEN = 258
EPOCH = 1000
BATCH_SIZE = 8
PHOBERT_BATCH_SIZE = 64
SGD_BATCH_SIZE = 512
EMBEDDING_DIM = 300
TRAINABLE = True
STOP_PATIENCE = 30
LR_PATIENCE = 15

# FILES
CNN_MODEL = 'CNN_MODEL.keras'
LSTM_MODEL = 'LSTM_MODEL.keras'
BILSTM_MODEL = 'BILSTM_MODEL.keras'
ENSEMBLE_CNN_BILSTM_MODEL = 'ENSEMBLE_CNN_BILSTM_MODEL.keras'
FUSION_CNN_BILSTM_MODEL = 'FUSION_CNN_BILSTM_MODEL.keras'
TRANSFORMER_MODEL = 'TRANSFORMER_MODEL.keras'
SGD_MODEL = 'SGD_MODEL.pkl'
KNN_MODEL = 'KNN_MODEL.pkl'
PHOBERT_FEATURES_TITLE = 'PhoBERT_features_title.npy'
PHOBERT_FEATURES_TEXT = 'PhoBERT_features_text.npy'

REPORT = 'phobert/reports/'
MODEL = 'phobert/models/'
MODEL_IMAGE = 'phobert/model_images/'
CHART = 'phobert/charts/'

CNN_REPORT = 'CNN_REPORT.txt'
LSTM_REPORT = 'LSTM_REPORT.txt'
BILSTM_REPORT = 'BILSTM_REPORT.txt'
ENSEMBLE_CNN_BILSTM_REPORT = 'ENSEMBLE_CNN_BILSTM_REPORT.txt'
FUSION_CNN_BILSTM_REPORT = 'FUSION_CNN_BILSTM_REPORT.txt'
TRANSFORMER_REPORT = 'TRANSFORMER_REPORT.txt'
SGD_REPORT = 'SGD_REPORT.txt'
KNN_REPORT = 'KNN_REPORT.txt'

CNN_IMAGE = 'CNN_IMAGE.png'
LSTM_IMAGE = 'LSTM_IMAGE.png'
BILSTM_IMAGE = 'BILSTM_IMAGE.png'
ENSEMBLE_CNN_BILSTM_IMAGE = 'ENSEMBLE_CNN_BILSTM_IMAGE.png'
FUSION_CNN_BILSTM_IMAGE = 'FUSION_CNN_BILSTM_IMAGE.png'
TRANSFORMER_IMAGE = 'TRANSFORMER_IMAGE.png'
SGD_IMAGE = 'SGD_IMAGE.png'
KNN_IMAGE = 'KNN_IMAGE.png'

CNN_CHART = 'CNN_CHART.png'
LSTM_CHART = 'LSTM_CHART.png'
BILSTM_CHART = 'BILSTM_CHART.png'
ENSEMBLE_CNN_BILSTM_CHART = 'ENSEMBLE_CNN_BILSTM_CHART.png'
FUSION_CNN_BILSTM_CHART = 'FUSION_CNN_BILSTM_CHART.png'
TRANSFORMER_CHART = 'TRANSFORMER_CHART.png'
SGD_CHART = 'SGD_CHART.png'
KNN_CHART = 'KNN_CHART.png'
