PATH = 'resources/'
MAX_LEN = 200
EPOCH = 1000
BATCH_SIZE = 4
EMBEDDING_DIM = 300
TRAINABLE = True
STOP_PATIENCE = 15
LR_PATIENCE = 15

# FILES
CNN_MODEL = 'CNN_MODEL.keras'
LSTM_MODEL = 'LSTM_MODEL.keras'
BILSTM_MODEL = 'BILSTM_MODEL.h5'
CNN_BILSTM_MODEL = 'CNN_BILSTM_MODEL.keras'
GLOVE_MODEL = 'GLOVE_MODEL.model'

REPORT = 'phobert/reports/'
MODEL = 'phobert/models/'
MODEL_IMAGE = 'phobert/model_images/'
CHART = 'phobert/charts/'

CNN_REPORT = 'CNN_REPORT.txt'
LSTM_REPORT = 'LSTM_REPORT.txt'
BILSTM_REPORT = 'BILSTM_REPORT.txt'
CNN_BILSTM_REPORT = 'CNN_BILSTM_REPORT.txt'

CNN_IMAGE = 'CNN_IMAGE.png'
LSTM_IMAGE = 'LSTM_IMAGE.png'
BILSTM_IMAGE = 'BILSTM_IMAGE.png'
CNN_BILSTM_IMAGE = 'CNN_BILSTM_IMAGE.png'

CNN_CHART = 'CNN_CHART.png'
LSTM_CHART = 'LSTM_CHART.png'
BILSTM_CHART = 'BILSTM_CHART.png'
CNN_BILSTM_CHART = 'CNN_BILSTM_CHART.png'
